// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSSH'](arg1, arg2, arg3);
}

export function SaveCSV(arg1) {
  return window['go']['main']['App']['SaveCSV'](arg1);
}
