// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSSH(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SaveCSV(arg1:string):Promise<void>;
